productToken: 
host_name: localhost
http_port: 8080
grpc_port: 8082
services:
    loms: 
        host_name: localhost
        port: 8081
    product:
        host_name: route256.pavl.uk
        port: 8080
db:
# for test: dsn: "host=localhost port=5432 dbname=checkout user=user password=password sslmode=disable"
    dsn: "host=pgcheckout port=5432 dbname=checkout user=user password=password sslmode=disable"
    max_open_connections: 10