productToken: 
host_name: localhost
http_port: 8080
grpc_port: 8082
services:
    loms: 
        host_name: localhost
        port: 8081
    product:
        host_name: route256.pavl.uk
        port: 8080